### ISSUE TITLE
Sponsor link = 404

### ISSUE THREAD

**Issue by deppy** [almnt/guide-to-allyship#23]
**Describe the bug**
Your sponsor link is a 404 😢 

**To Reproduce**
1. Click the [sponsor link](buymeacoffee/amelielamont) found in [FUNDING.yml:3](https://github.com/almnt/guide-to-allyship/blob/master/.github/FUNDING.yml#L3)
2. See error

**Expected behavior**
Takes me to a donation page

**Comment by almnt** [comment]
@deppy Ahhh, thanks for catching that. Will update right now. :)

**Comment by almnt** [comment]
Fixed! Thanks again @deppy! 😄
